/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dvbt_config.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6da2f5773024c57e658dc78d82377fcb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cemmse/dvbt_config.h>
// pydoc.h is automatically generated in the build directory
#include <dvbt_config_pydoc.h>

void bind_dvbt_config(py::module& m)
{

    // using dvbt_config    = gr::cemmse::dvbt_config;
    // py::class_<dvbt_config, gr::,
    //     std::shared_ptr<dvbt_config>>(m, "dvbt_config", D(dvbt_config))
    //     .def(py::init(&dvbt_config::make),
    //        D(dvbt_config,make)
    //     );

    py::enum_<::gr::cemmse::dvbt_hierarchy_t>(m, "dvbt_hierarchy_t")
        .value("NH", ::gr::cemmse::dvbt_hierarchy_t::NH)         // 0
        .value("ALPHA1", ::gr::cemmse::dvbt_hierarchy_t::ALPHA1) // 1
        .value("ALPHA2", ::gr::cemmse::dvbt_hierarchy_t::ALPHA2) // 2
        .value("ALPHA4", ::gr::cemmse::dvbt_hierarchy_t::ALPHA4) // 3
        .export_values();

    py::implicitly_convertible<int, ::gr::cemmse::dvbt_hierarchy_t>();
    py::enum_<::gr::cemmse::dvbt_transmission_mode_t>(m, "dvbt_transmission_mode_t")
        .value("T2k", ::gr::cemmse::dvbt_transmission_mode_t::T2k) // 0
        .value("T8k", ::gr::cemmse::dvbt_transmission_mode_t::T8k) // 1
        .export_values();

    py::implicitly_convertible<int, ::gr::cemmse::dvbt_transmission_mode_t>();

}








